server: 
  port: 9000
  
spring:
  application:
      name: zuul-novice
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        ip-address: ${HOST_ADDRESS:localhost}
        port: ${SERVER_PORT:${server.port}}
        healthCheckInterval: 15s
        instance-id: zuul-novice
        service-name: zuulNovice
        
zuul:
  # 动态filter
  groovy:
    filter: /com/rsoft/gw/filter/
  prefix: /api
  
  #api key auth
  apikey:
    enabled: true
    routes:
      test:
        alg: MD5
        header: authkey
        salt: 1234567890
        message: 服务忙,请稍后再试.
      uaa:
        alg: SHA
        expires: 60
        salt: abcdefghijk
  
  # 请求限流
  ratelimit:
    enabled: true
    behind-proxy: true
    policy-list:
      test:
        - limit: 5 
          refresh-interval: 60
          type: 
            #- user
            #- origin
            - url

  #debug switch
  debug:
    request: true
    parameter: true
    
  #路由定义
  routes:
    # 1.url pattern
    qq:
      path: /qq/**
      url: https://www.qq.com/
      #ssl-hostname-validation-enabled: false
      #sensitiveHeaders: Cookie,Set-Cookie,Authorization
      stripPrefix: true
    
    # 2.serviceId pattern
    userService: /uaa/**
    test:
      path: /test/*
      serviceId: testService
      stripPrefix: true
      